### ISSUE TITLE
Connection error is not properly caught (Promise is not properly rejected)

### ISSUE THREAD

**Issue by jhobz** [satanch/node-livesplit-client#2]
I'm using this library in the following fashion (simplified example):
```js
// library import
;(async () => {
	try {
		const client = new LiveSplitClient(`${nodecg.bundleConfig.url}:${nodecg.bundleConfig.port}`) // 127.0.0.1:16834

		client.on('connected', () => { /* Logging */ })
		client.on('disconnected', () => { /* Logging */ })
		
		await client.connect()
	} catch (err) {
		// Logging
		// The logs here are never triggered
	}
})()
```
It's basically the example page from this repo.

I need to detect if LiveSplit.Server is not running, but instead of the `client` Promise rejecting and the error being caught by the try/catch block, the connection error bleeds through and causes the program to exit with an error code.

```
Error: connect ECONNREFUSED 127.0.0.1:16834
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 16834
}
```

I'm guessing the code to handle an error in the socket connection is not properly catching the connection and rejecting the Promise? In other words, perhaps https://github.com/satanch/node-livesplit-client/blob/main/src/LiveSplitClient.js#L60 is not working as intended?

**Comment by satanch** [comment]
Thank you for your report! I will look into this next week.

**Comment by satanch** [comment]
You should use extra `try/catch` block at connection method call.
With new version you can check client connection status (`client.connected`), which could help you to easily get connection result. Also, don't forget about "error" event. So failed connection throws error, that's totally normal.
```js
(async () => {
    const client = new LiveSplitClient('127.0.0.1:16834');
    client.on('error', (err) => { console.log('Error from event:', err) });
    try {
        await client.connect();
    } catch (err) {
        console.error('Error from try/catch:', err);
    }
    console.log('We can do things later! Status:', client.connected ? 'connected' : 'not connected');
})();
```
This issue could be reopened, but everything is fine even in version 1.0.0 as I see.

**Comment by jhobz** [comment]
Ok yeah it appears that
```js
client.on('error', (err) => {
    // Handle the error here, in addition to connection attempt
}
```
is required to fully catch a socket connection error, even if you're using a `try/catch` block around the `client.connect()` call. I didn't realize that, thanks for your help!

I think this isn't very apparent from the example code. Perhaps an update should be made to the README to include that line in the example? And/or a section could be added to the API docs to include which events are emitted by `LiveSplitClient`? As of right now the only way to know about more than `'connected'` or `'disconnected'` is to dig into the code.

Thanks for making this library by the way!
