### ISSUE TITLE
Small typo in property from `getAll`

### ISSUE THREAD

**Issue by jhobz** [satanch/node-livesplit-client#3]
There's a small typo for one of the getters, which leads to that typo being propagated to the object returned by the `.getAll()` function. `getPreviousSplitname` should be `getPreviousSplitName` to keep consistent camelCase with `getCurrentSplitName`. Minor thing, but figured I'd mention it as it caused me to trip up a bit at one point.

Relevant lines:
function definition: https://github.com/satanch/node-livesplit-client/blob/49636e23795592754a7b5b5d679cb3af7c241433/src/LiveSplitClient.js#L331
usage in `.getAll()`: https://github.com/satanch/node-livesplit-client/blob/49636e23795592754a7b5b5d679cb3af7c241433/src/LiveSplitClient.js#L350

**Comment by satanch** [comment]
Fixed in https://github.com/satanch/node-livesplit-client/commit/df280d726f5fc9cf5690c91f44a24a466e5f1a25
You can test it by yourself, before package will be published to NPM.

**Comment by jhobz** [comment]
Confirmed working and now named as expected for me locally. 👍
